INSERT INTO NPL_USUARIO (ID, NOME, LOGIN, SENHA, EMAIL) VALUES (1, 'caio', 'caio123','1234','caio@123');

ALTER SEQUENCE NPL_USUARIO_ID_SEQ RESTART WITH 2;

INSERT INTO NPL_PERFIL(ID, DESCRICAO) VALUES (1, 'DEV');

ALTER SEQUENCE NPL_PERFIL_SEQ RESTART WITH 2;